### ISSUE TITLE
Are permissions correct?

### ISSUE THREAD

**Issue by thblt** [lamby/pkg-nix#2]
Users can not query nix-env (`error: Nix database directory ‘/var/nix/db’ is not writable: Permission denied`), but it seems that channel configuration is per-user:

```
 $ nix-channel --list     
nixpkgs https://nixos.org/channels/nixpkgs-unstable
 $ sudo nix-channel --list
 $
```

**Comment by lamby** [comment]
Did you follow the instructions in ``README.Debian``?

**Comment by thblt** [comment]
No, it wasn't present in my initial clone, for some reason. It seems to have solved the issue. Maybe it could be nice to point to it in the package description, do you want a PR for that?

**Comment by lamby** [comment]
``README.Debian`` has been in there for a while, so not sure how you missed it.

> it could be nice to point to it in the package description

This is not typically done in Debian packages, otherwise almost every package would have such a pointer.

**Comment by thblt** [comment]
> README.Debian has been in there for a while, so not sure how you missed it.

I'm almost certain there were only two commits on the repo yesterday, and README.Debian appeared in my clone by pulling this morning.  I've done a `find` before and after pulling, just to make sure.  If you're sure it was already pushed, maybe that's a cache issue or something similar, idk...

> This is not typically done in Debian packages,

True, but most packages which require specific post-install configuration or special attention to the documentation usually specify it. I really think it would improve usability of the package, with no extra cost :)

**Comment by thblt** [comment]
Another thing: there's a serious difference in packages installation time between my Macbook Air 2011 (not really a powerful beast, by all standards) running Nix installed through `curl | bash` as specified in the Nix manual, and my Mac Pro 2008 (8x2.8Ghz Xeon cores, 10GB RAM) with your packaged Nix.  Both run Debian Stretch, with more or less the same general configuration. Yet, the Macbook Air took maybe a few minutes to install Krita, where the Pro has been working on it for more than an hour now, and seems far from finished.  There's a lot of ´cc1` and `cc1plus` activity in `top`, which leads me to think a lot of things are built from source.   I don't know if it has to do with your package or with the way Nix behaves.

A probably significant difference is that `curl | bash` installs a single user Nix (`/nix` is owned by the user which does the installation), where your package installs a multi-user version.  

I understand some of my questions may be really beginner-level, please tell me if I should  rather  use Nix from the official installation method and  try your package again later :-)

**Comment by lamby** [comment]
Please file as a new issue..
