### ISSUE TITLE
Security vulnerability fixed upstream 1.11.10

### ISSUE THREAD

**Issue by aij** [lamby/pkg-nix#6]
Users can modify / interfere with builds by other users on multi-user systems

https://groups.google.com/forum/#!topic/nix-security-announce/oXnpAOSK4ws

**Comment by lamby** [comment]
Thanks for the heads-up. I've fixed this in ac7285d6745b8dc6891000797ddca20b6b55b600 :)

**Comment by aij** [comment]
Wow, thanks for the quick turnaround. I had to install libseccomp-dev to get it to build though. That should probably go in Build-depends?


```
configure:6845: checking for LIBSECCOMP
configure:6852: $PKG_CONFIG --exists --print-errors "libseccomp"
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
```

**Comment by lamby** [comment]
> I had to install libseccomp-dev to get it to build though

Filed as #7. Separate tickets for separate issues please! ;)
